name: serendipity_pass
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.1
  fluttertoast: ^8.2.5
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - resources/
    - resources/images/


# 应用图标
flutter_icons:
  android: true
  ios: true
  image_path: resources/images/env/default.png